services:
  - type: web
    name: urbanpulse-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "mysql+pymysql://root:password@localhost/urbanpulse"
      - key: OPENWEATHER_KEY
        value: "de06e1267ed99ce53c8d5eba93de638a"
      - key: TOMTOM_KEY
        value: "9AJSHZwsSKPHm9yFsCmmUrn6FFLUDgUh"
      - key: OPEN_METEO_URL
        value: "https://air-quality-api.open-meteo.com/v1/air-quality?latitude=12.97&longitude=77.59&hourly=pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,ozone"
